version: '3'

services:
        reverse-proxy:
                image: traefik:v2.5
                command:
                        - --api.insecure=true
                        - --providers.docker=true
                        - --providers.docker.exposedbydefault=false
                        - --certificatesresolvers.le.acme.email=uwalexaskills@gmail.com
                        - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
                        - --certificatesresolvers.le.acme.tlschallenge=true
                        - --entrypoints.web.address=:80
                        - --entrypoints.websecure.address=:443
                        - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
                        - --entrypoints.web.http.redirections.entryPoint.to=websecure
                        - --entrypoints.web.http.redirections.entryPoint.scheme=https
                        - --entrypoints.web.http.redirections.entryPoint.permanent=true

                ports:
                        - 80:80
                        - 443:443
                        - 8080:8080
                volumes:
                        - "./letsencrypt:/letsencrypt"
                        - /var/run/docker.sock:/var/run/docker.sock
