version: '3'
services:
        api:
                build: .
                labels:
                        - "traefik.enable=true"
                        - "traefik.http.routers.api.rule=Host(`api.uwalexaskills.org`)"
                        - "traefik.http.services.api.loadbalancer.server.port=80"
                        - "traefik.docker.network=traefik_default"
                        - "traefik.http.routers.api.tls=true"
                        - "traefik.http.routers.api.tls.certresolver=le"
                networks:
                        - traefik_default

networks:
        traefik_default:
                external: true