CREATE TABLE IF NOT EXISTS WebUsers (
    username TEXT UNIQUE PRIMARY KEY NOT NULL,
    salt BYTEA NOT NULL,
    hash BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
    uid uuid UNIQUE PRIMARY KEY NOT NULL,
    alexaId BYTEA UNIQUE NOT NULL,
    alexaDevice TEXT NOT NULL,
    email TEXT,
    lastUpdated CURRENT_TIME
);

