version: '3'
services:
        admin:
                build: .
                labels:
                        - "traefik.enable=true"
                        - "traefik.http.routers.admin.rule=Host(`admin.uwalexaskills.org`)"
                        - "traefik.http.services.admin.loadbalancer.server.port=80"
                        - "traefik.docker.network=traefik_default"
                        - "traefik.http.routers.admin.tls=true"
                        - "traefik.http.routers.admin.tls.certresolver=le"
                networks:
                        - traefik_default

networks:
        traefik_default:
                external: true