version: '3'
services:
        web:
                build: .
                labels:
                        - "traefik.enable=true"
                        - "traefik.http.routers.web.rule=Host(`uwalexaskills.org`)"
                        - "traefik.http.services.web.loadbalancer.server.port=80"
                        - "traefik.docker.network=traefik_default"
                        - "traefik.http.routers.web.tls=true"
                        - "traefik.http.routers.web.tls.certresolver=le"
                networks:
                        - traefik_default

networks:
        traefik_default:
                external: true